### ISSUE TITLE
HIPPO texture analysis examples do not work for multi-atom CIFs

### ISSUE THREAD

**Issue by Svennito** [lanl/MILK#11]
The lines

        if i > 0:
            editor.ref(key1='Biso', key2='Biso', value='0 1 100000', sobj1=phases[0], sobj2=phase)
        else:
            editor.set_val(key='Biso', sobj=phase, value='0.6')

do not work once a CIF file has multiple atoms. Can they be made more general, i.e. loop over all atoms in a structure?

**Comment by Svennito** [comment]
As a second issue, the initial values for the peak broadening parameters are IMHO too broad. Instead of 
        editor.set_val(key='MicroStrain', sobj=phase, value='0.002')
        editor.set_val(key='CrystSize', sobj=phase, value='500')
they should be something like
        editor.set_val(key='MicroStrain', sobj=phase, value='8e-4')
        editor.set_val(key='CrystSize', sobj=phase, value='1000')

The current parameters make peaks too broad, setting them up to get even broader. Should be on the skinnier side...

**Comment by djm87** [comment]
Sven, will revisit the tutorial.. 

For the multi atom bit, have you tried using multiple sobs inputs. You can create a chain of strings seperated by spaces that must be in the subordinate object string e.g. sobj="str1 str2 str3"

If I have 3 subordinate object names they are all concatenated like "subordinate_object1subordinate_object2subordinate_object3" and I assert that str1 and str2 and str3 are in the object and assert that any nsobj="str4 str5..." are not in the subordinate objects names.

**Comment by djm87** [comment]
I think I now understand the problem you are referring to.. I've made changes to the example to address it. The following code snippet makes the first biso in the parameter file the referenced bison and all others the tied to it 
```python
    editor.set_val(key='Biso', sobj='First', value='0.6')
    editor.ref(key1='Biso', key2='Biso', value='0 1 100000', nsobj1='First',sobj2='First')
```

I tried starting with a narrower peak width and the fit is good, but I think there is actually anisotropic peak broaden in the run001 case.
