### ISSUE TITLE
booboo in HIPPO example

### ISSUE THREAD

**Issue by Svennito** [lanl/MILK#19]
The line 
`
 editor.free(key='Biso')
`
will not refine Biso, the correct key is "_B_iso_"...

**Comment by djm87** [comment]
This should not have been an issue since d['Biso'] = '_atom_site_B_iso_or_equiv' is a dictionary key. Are you sure it wasn't because of some tie or something else? I've confirmed    editor.free(key='Biso') does set the _atom_site_B_iso_or_equiv key to be refined.
