### ISSUE TITLE
2_setup.py not handling spaces in section title

### ISSUE THREAD

**Issue by Svennito** [lanl/MILK#23]
milk.json has a line

        "section_title": "Zr-2.5Nb full texture",
this leads to an error:

2_setup.py: error: unrecognized arguments: full texture01

Suggest to replace spaces with underscores.

**Comment by djm87** [comment]
Fixed by replacing spaces with underscores. There are other places this space thing is popping up because of the old parse args interface. At some point I will update the interfaces and spaces won't cause issues anywhere.
