### ISSUE TITLE
Windows maud path definition bug

### ISSUE THREAD

**Issue by nepeters** [lanl/MILK#26]
Dan, great work with this. I think I found a bug for the windows setup process. 

I could not get the MAUD_PATH env variable to correctly set. I think that the bat_install function in config_maud.py needs to write a ".bat" file instead of a ".sh" file. Also, the syntax to define an environment variable is different depending on whether you are using cmd or PowerShell. for a default anaconda installation, it should setup an Anaconda PowerShell and an Anaconda CMD prompt, so it might be good to add compatibility for both. 

The current "set MAUD_PATH={maud_path} works with CMD only. For PowerShell, the syntax in the python code I think needs to be $env:MAUD_PATH={maud_path}. I think you could probably add in an if/then statement to cover both options in the .bat file. 

Ah the joys of using windows.. Let me know if you want me to submit a pull request or something.

**Comment by Svennito** [comment]
Hey Nate - thanks!

Hey Dan - There’s code in GSAS language when it says “I think I run on….”
to call the right commands if you need something platform dependent ? I
think it’s gsas_done or so….

**Comment by djm87** [comment]
Nate, get off Window already! Thanks for the info, I'll incorporate the change with the version I'm pushing for the paper and close this thread once it is done.

**Comment by ZhangxiJesseFeng** [comment]
In addition, after activating conda environment "conda activate MILK", the command for windows on cmd.exe is:
python config_maud.py -pm "PATH\TO\Maud\"
The current instructions suggests config_maud.py -p "PATH\TO\Maud\maud"

**Comment by djm87** [comment]
Jesse, what was your installation - WSL or conda command line environment? I think to support windows going forward I'm going to leverage visual studio and which can integrate WSL for bash goodness.

**Comment by ZhangxiJesseFeng** [comment]
I am using windows command line conda environment. Not WSL.

Zhangxi "Jesse" Feng
UNH Mechanical Engineering



-------- Original message --------
From: Daniel Savage ***@***.***>
Date: 4/24/23 6:23 PM (GMT-05:00)
To: lanl/MILK ***@***.***>
Cc: Zhangxi Feng ***@***.***>, Comment ***@***.***>
Subject: Re: [lanl/MILK] Windows maud path definition bug (Issue #26)


CAUTION: This email originated from outside of the University System. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Jesse, what was your installation - WSL or conda command line environment? I think to support windows going forward I'm going to leverage visual studio and which can integrate WSL for bash goodness.

**Comment by djm87** [comment]
These issue should have been addressed with recent windows tutorials and commits.
