### ISSUE TITLE
Running Cinema server using Visual Studio Code terminal makes the terminal not responsive to terminate task

### ISSUE THREAD

**Issue by ZhangxiJesseFeng** [lanl/MILK#29]
It seems that since the task is running outside the terminal, the terminal does not recognize that it is even running a task. The option to terminate task is greyed out. Maybe we should add a stand-alone way of terminating the cinema server.

**Comment by djm87** [comment]
Address in most recent commit ab29bc107b403fa02b1b541a3cad4d80360d9b41
