### ISSUE TITLE
milk environment built with environment_milk.yml is missing pathos

### ISSUE THREAD

**Issue by ZhangxiJesseFeng** [lanl/MILK#30]
For at least example 4: CHESS-GE, pathos is required but it is removed because Spotlight is currently removed for Windows.

I resolved it by adding Pathos back to pip install section for milk. Everything works.

Please confirm and I can push this.

**Comment by nepeters** [comment]
Chris made another release for spotlight which should work now on Windows. v0.10.2. You could try adding that back into the yaml file and confirm that the install works. Conda solve was running very slow for me, took over an hour.

**Comment by ZhangxiJesseFeng** [comment]
I installed on WCP using the full environment yaml. It solved in a few minutes. And everything so far seems to work.
