### ISSUE TITLE
Windows uses batch script different from Unix bash script

### ISSUE THREAD

**Issue by ZhangxiJesseFeng** [lanl/MILK#33]
Should we just include both tutorial.sh and tutorial.bat in the folder and instruct the user to use the appropriate one?

**Comment by djm87** [comment]
Yes. I pushed for The APS hydra texture a bat file that seems to work. Please test and close if all good.

**Comment by ZhangxiJesseFeng** [comment]
The separate bat script is good and I also updated the wiki pages.
